trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/*
    - pipelines/azure-pipelines.yml

variables:
  app_name: '$(name_prefix)-$(name_base)-$(name_suffix)'
  acr_name: '$(name_prefix)$(name_base)$(name_suffix)acr'
  image_name: 'mywebapp'
  acr: '$(acr_name).azurecr.io/$(image_name)'
  tagged: '$(acr):$(Build.BuildId)'
  latest: '$(acr):latest'

stages:

- stage: Prerequisites
  jobs:
  - job: Infrastructure
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: jlorich.TerraformCli.5619d23d-fb03-4459-a295-5958fd240452.TerraformCli@0
      displayName: Terraform Infra
      inputs:
        targetAzureSubscription: 'CDW - Microsoft AIRS 01'
        script: 'terraform apply -auto-approve -var="name_prefix=$(name_prefix)" -var="name_base=$(name_base)" -var="name_suffix=$(name_suffix)"'
        targetStorageAccountName: cdwterraformstate
        backendContainerName: learnazdo
        backendStateFileKey: '$(name_prefix)$(name_base)$(name_suffix).tfstate'
        workingDirectory: './terraform'

- stage: Build
  jobs:
  - job: Container
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@1
      displayName: 'Build Container'
      inputs:
        azureSubscription: 'CDW - Microsoft AIRS 01'
        scriptLocation: inlineScript
        inlineScript: |
          sed -i 's/XXX/$(Build.BuildId)/g' ./src/index.html
          az acr build -r $(acr_name) -t $(tagged) -t $(latest) -f ./src/Dockerfile ./src/

- stage: Staging
  jobs:
  - deployment: WebApp
    displayName: Deploy Web App
    pool:
      vmImage: 'ubuntu-latest'
    environment: Staging
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy Web App'
            inputs:
              azureSubscription: 'CDW - Microsoft AIRS 01'
              appName: '$(app_name)-stage'
              containers: '$(tagged)'

- stage: Production
  jobs:
  - deployment: WebApp
    displayName: Deploy Web App
    pool:
      vmImage: 'ubuntu-latest'
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy Web App'
            inputs:
              azureSubscription: 'CDW - Microsoft AIRS 01'
              appName: '$(app_name)-prod'
              containers: '$(tagged)'